set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

# Yank to system clipboard using wl-copy
# bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

# Yank to system clipboard using xclip
# bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

# Reload config
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

# Use vi-style key bindings in copy mode
set-window-option -g mode-keys vi

# Vim-style selection and copying
bind-key -T copy-mode-vi v send-begin-selection
bind-key -T copy-mode-vi y send-copy-selection-and-cancel

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vim style pane selection without prefix
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Shift Alt J/K to switch sessions
bind -n M-J switch-client -p
bind -n M-K switch-client -n

# ===== General Style =====
set-option -g status-position top
set-option -g status-interval 5
set-option -g status-justify centre
set-option -g status-style "bg=default fg=white"

# ===== Window Styles =====
# Inactive windows
set-window-option -g window-status-format " #I #W "
# Active window
set-window-option -g window-status-current-format "#[bg=green,fg=black,bold] #I #[bg=black,fg=green] #W "
set-window-option -g window-status-separator ""

# ===== Left Status Bar: Session Info =====
set-option -g status-left-length 30
set-option -g status-left "#[bg=black,fg=blue,bold] #S #[default]#[bg=blue,fg=black,bold]  #[bg=default,fg=blue]"

# ===== Right Status Bar =====
set-option -g status-right-length 30
# set-option -g status-right "#[bg=green, fg=black,bold]  #(basename #{pane_current_path}) "
set-option -g status-right "#[bg=default,fg=magenta]#[bg=magenta,fg=black,bold] #[bg=black,fg=magenta,bold] #(basename #{pane_current_path}) "
# set-option -g status-right "#[bg=red, fg=black,bold]  #[bg=green, fg=black,bold] #(whoami) "

# ===== Pane Borders (Optional) =====
set-option -g pane-border-style "fg=colour8"
set-option -g pane-active-border-style "fg=green"

# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-yank'
#
# run '~/.tmux/plugins/tpm/tpm'
